# 1. Create a 3x3x3 array with random values 

In [3]:
arr = np.random.uniform((3,3,3))
print (arr)


[1.42141402 1.28022552 1.27679566]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
ar = np.diag(1+np.arange(4), k = -1)
print (ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
a = np.zeros ((8,8), dtype=int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print (a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
arr = np.random.random((5,5))
arrmax, arrmin = arr.max(), arr.min()
arr= (arr-arrmin)/(arrmax-arrmin)
print (arr)

[[0.05822565 0.69648189 0.35724274 0.8698517  1.        ]
 [0.04071932 0.52934407 0.20792486 0.56022257 0.95672703]
 [0.15432353 0.86715209 0.01697916 0.82225749 0.16670237]
 [0.94313669 0.120212   0.10082079 0.9674203  0.77095603]
 [0.77620991 0.55382634 0.50153351 0.26337859 0.        ]]


# 5.  How to find common values between two arrays?

In [7]:

array1 = np.array([0, 10, 20, 40, 60])
print(array1)
array2 = [10, 30, 40]
print(array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

[ 0 10 20 40 60]
[10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [17]:
x = np.random.randint(2,3,6)
print(x)
y = np.random.randint(2,3,6)
print(y)
array_equal = np.allclose(x, y)
print(array_equal)

[2 2 2 2 2 2]
[2 2 2 2 2 2]
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.28923253 0.69809269 0.01316654 0.         0.14146221 0.32077872
 0.06701745 0.23287205 0.4051064  0.59393671]


# 9. How to print all the values of an array?

In [25]:

Z = np.random.random((10,10))
print(Z)

[[0.97880665 0.06013717 0.08390044 0.39290111 0.47035761 0.47950206
  0.71287054 0.95997268 0.04040018 0.07161649]
 [0.49953932 0.69378524 0.44162007 0.73679852 0.69340553 0.32202403
  0.45735306 0.40085739 0.3182183  0.72890819]
 [0.82539276 0.6236267  0.64044497 0.54732153 0.36308218 0.63501276
  0.19994941 0.93788355 0.3359913  0.3950859 ]
 [0.24325282 0.13588768 0.89007375 0.21202565 0.82810185 0.58255225
  0.71652352 0.1793262  0.4682044  0.32632143]
 [0.4164612  0.8174177  0.18095107 0.60212637 0.16955397 0.21775467
  0.02698195 0.92580159 0.58852634 0.92287208]
 [0.55017215 0.57820656 0.36178606 0.84142862 0.32893991 0.33077943
  0.16214499 0.90313583 0.96801175 0.58863618]
 [0.4458354  0.60057899 0.4524276  0.82696088 0.00623696 0.96362898
  0.98986769 0.51699483 0.86499593 0.3421328 ]
 [0.55401745 0.84959882 0.82397485 0.21607064 0.55257334 0.60783634
  0.75010674 0.3155251  0.14573007 0.01779072]
 [0.00797792 0.18423063 0.67263495 0.72456043 0.14783773 0.12501836
  0.73111036

# 10.Subtract the mean of each row of a matrix

In [27]:
X = np.random.rand(5, 10)


Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.53894627 -0.08708262  0.32899325 -0.37871716 -0.33521617  0.229276
  -0.2031882   0.17934309 -0.09642457 -0.17592989]
 [-0.18210891 -0.35305383  0.24347925  0.05966788 -0.08495848  0.50592041
  -0.04069833  0.03217497  0.08994011 -0.27036306]
 [-0.35602037  0.42291862  0.08445269 -0.17631927  0.22654266 -0.04589745
   0.01248304 -0.06135595 -0.24258148  0.13577751]
 [ 0.25241546  0.38008482 -0.01452237 -0.48521895  0.04372499 -0.17672564
  -0.11098403 -0.0077454   0.43172252 -0.31275141]
 [-0.48038469  0.12206428 -0.22220561 -0.22038017  0.33037963 -0.26006761
   0.46325196  0.050038    0.12527808  0.09202614]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 3. 2. 1. 3. 6. 5. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [31]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", A, B)

array([89, 23, 23])

# 13.How to find the most frequent value in an array?

In [32]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[7 6 9 3 4 3 0 9 8 9 7 1 7 9 0 4 4 7 4 3 1 2 7 6 0 5 6 4 7 9 1 8 4 0 9 7 6
 6 0 8 9 7 6 1 4 7 0 8 2 5]
rank: 7


# 14.How to get the n largest values of an array

In [33]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [34]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
